### ISSUE TITLE
微信2.9.5输入栏不显示文字

### ISSUE THREAD

**Issue by thep0y** [abcfy2/deepin-wine5-aur#1]
输入时，连光标都没有，一片空白，但打完字后回车发送是正常的

**Comment by abcfy2** [comment]
我这边不能重现，我本地是好的，看看wine终端有什么输出吧。另外可以用deepin看看是否有这个问题。对于deepin上游就有的问题我暂时没办法解决。

我这边用的是系统是Manjaro KDE，暂时没这个问题，能否截图下你的故障看看？

**Comment by thep0y** [comment]
我也是manjaro kde，输入框就是一片白，截图也看不出什么来
![20200708230906](https://user-images.githubusercontent.com/51874567/86936028-0d307980-c170-11ea-97b0-94f821fbd039.png)

**Comment by abcfy2** [comment]
试试用`winetricks`装下`riched20`这个包，参考命令:

```shell
# WINEPREFIX替换成你的deepin-wine的prefix，如果是默认的~/.wine的话可以不指定这个环境变量
WINEPREFIX=~/.deepin-wine/Deepin-Wechat WINE=deepin-wine5 winetricks riched20
```

另外你的微信是怎么装的？直接下载官方安装包装的吗？我记得[depin-wine-wechat](https://aur.archlinux.org/packages/deepin-wine-wechat/)这个AUR是直接从deepin上游的deb包解出来的，里面已经带有riched20了，你也可以装那个AUR之后运行环境替换成deepin-wine5

**Comment by thep0y** [comment]
> 试试用`winetricks`装下`riched20`这个包，参考命令:
> 
> ```shell
> # WINEPREFIX替换成你的deepin-wine的prefix，如果是默认的~/.wine的话可以不指定这个环境变量
> WINEPREFIX=~/.deepin-wine/Deepin-Wechat WINE=deepin-wine5 winetricks riched20
> ```
> 
> 另外你的微信是怎么装的？直接下载官方安装包装的吗？我记得[depin-wine-wechat](https://aur.archlinux.org/packages/deepin-wine-wechat/)这个AUR是直接从deepin上游的deb包解出来的，里面已经带有riched20了，你也可以装那个AUR之后运行环境替换成deepin-wine5

谢谢，已经好了，应该是替换了riched20后没有注册，所以一直没生效。

**Comment by abcfy2** [comment]
解决了就好

**Comment by thep0y** [comment]
今日卸载wine后问题重现，执行你的那行命令提示wineserver not found!
请问riched20还有别的办法下载吗？

**Comment by abcfy2** [comment]
你的微信到底使用`wine`运行的还是`deepin-wine5`运行的？wine的命令不要反复切换，一般推荐你不同的wine使用不同的`WINEPREFIX`管理。

你尝试删掉旧的WINEPREFIX重新初始化吧

**Comment by abcfy2** [comment]
一个简单的方案是安装[deepin-wine-wechat](https://aur.archlinux.org/packages/deepin-wine-wechat/)，它在切换使用`deepin-wine`的时候会自动帮你删掉旧的WINEPREFIX重新初始化。

你可以尝试使用脚本自带的切换deepin-wine的方案，然后手改`run.sh`脚本，把原来的`deepin-wine`替换成`deepin-wine5`就行了
