### ISSUE TITLE
无法下载https://community-packages.deepin.com/deepin/pool/non-free/u/udis86/udis86_1.72-2_i386.deb

### ISSUE THREAD

**Issue by XiaoHuoZZ** [abcfy2/deepin-wine5-aur#11]
当使用ysy -S deepin-wine5时出现以下错误
无法下载https://community-packages.deepin.com/deepin/pool/non-free/u/udis86/udis86_1.72-2_i386.deb
貌似deepin社区已经没有这个版本的包了

**Comment by abcfy2** [comment]
好像小版本升级了： https://community-packages.deepin.com/deepin/pool/non-free/u/udis86/

**Comment by abcfy2** [comment]
另外这个包的下载是依赖了[deepin-udis86](https://aur.archlinux.org/packages/deepin-udis86/)，需要依赖方进行修复。如果依赖方实在不愿意继续维护，我考虑去掉这个依赖算了，反正感觉虽然deepin-wine5官方deb包依赖有这玩意，实际有没有这个东西都能正常工作，感觉没多少wine程序会真正需要这个

**Comment by XiaoHuoZZ** [comment]
> 另外这个包的下载是依赖了[deepin-udis86](https://aur.archlinux.org/packages/deepin-udis86/)，需要依赖方进行修复。如果依赖方实在不愿意继续维护，我考虑去掉这个依赖算了，反正感觉虽然deepin-wine5官方deb包依赖有这玩意，实际有没有这个东西都能正常工作，感觉没多少wine程序会真正需要这个

哈哈刚来arch,感觉每层依赖都不能出错，我是安装aur的qq卡住了一路找到这

**Comment by abcfy2** [comment]
> > 另外这个包的下载是依赖了[deepin-udis86](https://aur.archlinux.org/packages/deepin-udis86/)，需要依赖方进行修复。如果依赖方实在不愿意继续维护，我考虑去掉这个依赖算了，反正感觉虽然deepin-wine5官方deb包依赖有这玩意，实际有没有这个东西都能正常工作，感觉没多少wine程序会真正需要这个
> 
> 哈哈刚来arch,感觉每层依赖都不能出错，我是安装aur的qq卡住了一路找到这

你可以添加archlinuxcn源安装
