### ISSUE TITLE
deepin-wine5和deepin-wine5-stable有什么区别吗

### ISSUE THREAD

**Issue by Sakura-gh** [abcfy2/deepin-wine5-aur#13]

**Comment by abcfy2** [comment]
软件仓库不同。deepin-wine5是deepin旧版本的仓库中的包。现在deepin换了新的仓库了，deepin-wine自己也改了又改，从bundle到每个wine应用中，后来单独剥离出来放到了deepin的新仓库中，包名就叫deepin-wine5-stable
