### ISSUE TITLE
[Feature] 考虑在 tools 中加入 provides=('wine')

### ISSUE THREAD

**Issue by bryango** [abcfy2/deepin-wine5-aur#2]
https://github.com/abcfy2/deepin-wine5-aur/blob/bcfe01e49c8a4d6fa6402f07ea21fc597d2f5e30/PKGBUILD#L75-L79

考虑将 conflicts 一行改为：

```shell
 conflicts=('wine') 
 provides=('wine')
```

这样可以安装正常的 winetricks. 参见：https://wiki.archlinux.org/index.php/PKGBUILD#provides

**Comment by abcfy2** [comment]
之前考虑过，我在我本地的一版确实是这么写过，后来想想去掉了。

因为这个`deepin-wine5`给我感觉更像是一个实验中的开发版，官方很多和wine以及deepin-wine的冲突都没解决，都没重命名，你可以看我的PKGBUILD都是手工重命名避免文件冲突的，而且目前来看并未比`wine`有太多实质性的改进，因此有理由相信这个更多只是开发版。

我原本的打算是等官方进一步升级，把这些完善之后再加上的。另外你看的那部分是`deepin-wine5-tools`这个包的构建，这个包会将`deepin-wine5`做软链接到`wine`，因此会和`wine`有冲突，肯定会重名，所以才加上了`conflicts`，我个人其实不太建议在目前就装`deepin-wine5-tools`这个包的，我在`README.md`也确实是这么写的。我目前就是`wine`和`deepin-wine5`都装，有时候轮流切换对比下运行效果。

还有就是deepin-wine5的版本其实也不算高，很多`winetricks`的包都有警告，说是版本太低了，因此暂时也没有把这个`provider`加上

**Comment by bryango** [comment]
嗯嗯，有道理！这个问题还是暂时搁置比较好，我刚刚才发现 `deepin-wine5-tools` 的 symlink 根本就是错的 :joy: 链到了一个不存在的位置：
```shell
$ ll | grep '\-> deepin'
lrwxrwxrwx  1 root root         17  7月 28 21:03 wine -> deepin-wine5/wine
lrwxrwxrwx  1 root root         27  7月 28 21:03 wine-preloader -> deepin-wine5/wine-preloader
```
正确的应该是 `../lib/deepin-wine5/wine`, 所以这个包根本不 work... 还是等官方更新再说吧.

**Comment by abcfy2** [comment]
估计要等很久，目前deepin的重心根本不在完善deepin-wine上，旧的2.18版本还能用的情况下，应该是更多重心会放在迭代V20和UOS上，deepin-wine5的更新估计会等相当久

**Comment by abcfy2** [comment]
`deepin-wine5-tools`这个包似乎已经被官方废弃，在新的仓库路径下已经search不到了。所以这个issue暂时关闭
