### ISSUE TITLE
deepin-wine5的winecfg是不是不支持

### ISSUE THREAD

**Issue by rayd1oo** [abcfy2/deepin-wine5-aur#4]
最近发现deepin-wine5下运行微信可以发图了，但是有一个问题就是dpi缩放失效了
于是我想打开winecfg但是

我如果使用命令
`deepin-wine5 winecfg`
打开的是我本机安装的wine-staging的winecfg，而不是deepin-wine5的winecfg

但是我发现在安装万deepin-wine5之后多了一个二进制文件deepin5-winecfg
我尝试运行之后报错
```zsh
002c:fixme:winediag:start_process Wine Staging 5.9 is a testing version containing experimental patches.
002c:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
0050:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0034:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
002c:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
00c0:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
00c0:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
00c0:fixme:dwmapi:DwmIsCompositionEnabled 6D95DD14
00c8:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0df537, context 0x12bbd90, init_notify 0, handle 0x1acfce8): stub
00c0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0114:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
wine: configuration in L"/home/ray/.wine" has been updated.
0024:err:module:__wine_process_init L"C:\\windows\\system32\\deepin5-winecfg.exe" not found
```

请问该如何解决呢

**Comment by abcfy2** [comment]
我咋记得我本地也是`deepin-wine5 winecfg`运行的？等我开个干净的虚拟环境测试下

**Comment by abcfy2** [comment]
试了下没问题啊，你看我的截图，命令行运行的就是`deepin-wine5 winecfg`，看到关于的版本就是deepin-wine5的版本

专门用vagrant启动了一个纯净的archlinux运行看了下，只使用`yay -S deepin-wine5`安装`deepin-wine5`，并没有安装`wine`。我本地的环境是`deepin-wine5`和`wine`都安装了，平时也混用，没有任何问题，你的问题不能重现

![VirtualBox_archlinux_default_1596076501004_14974_30_07_2020_11_38_29](https://user-images.githubusercontent.com/5327677/88877960-564c8880-d259-11ea-96d2-7fa36e705d2c.png)

**Comment by rayd1oo** [comment]
> 试了下没问题啊，你看我的截图，命令行运行的就是`deepin-wine5 winecfg`，看到关于的版本就是deepin-wine5的版本
> 
> 专门用vagrant启动了一个纯净的archlinux运行看了下，只使用`yay -S deepin-wine5`安装`deepin-wine5`，并没有安装`wine`。我本地的环境是`deepin-wine5`和`wine`都安装了，平时也混用，没有任何问题，你的问题不能重现
> 
> ![VirtualBox_archlinux_default_1596076501004_14974_30_07_2020_11_38_29](https://user-images.githubusercontent.com/5327677/88877960-564c8880-d259-11ea-96d2-7fa36e705d2c.png)
> 

我找到问题了，deepin-wine5 winecfg默认打开了$HOME/.wine里面的winecfg 有没有办法修改默认的环境目录呢

**Comment by abcfy2** [comment]
加上WINEPREFIX环境变量指定新的路径就行了，我的截图第一次运行的命令也是总新的路径运行
