### ISSUE TITLE
deepin-wine5-tools 软连接错误

### ISSUE THREAD

**Issue by Aynamic** [abcfy2/deepin-wine5-aur#5]
deepin-wine5-tools这个软件包的 /bin/wine 和 /bin/wine-preloader 软链接错误

**Comment by abcfy2** [comment]
这个包已经废弃了，我已经删了。deepin上游都没这个包了，我的README应该也改了，都不提这个包了

**Comment by abcfy2** [comment]
并不能说没有这个包了，应该只是废弃了。deepin-wine5新版本发布到新的目录下去了，新目录下并没有deepin-wine5-tools，deepin仓库中的deepin-wine5-tools也是旧版本旧目录，应该是放弃维护了
